; Réglages sandbox (dev-friendly). À durcir pour la prod.
display_errors = On
error_reporting = E_ALL
date.timezone = Europe/Paris

; Envoi de mail via msmtp -> Mailpit.
sendmail_path = "/usr/bin/msmtp -t"

upload_max_filesize = 32M
post_max_size = 32M
memory_limit = 256M
